version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
      - textfile:/var/lib/node_exporter/textfile_collector
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - oncall-web
    networks:
      - iris

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.mdadm'
      - '--no-collector.ipvs'
      - '--no-collector.infiniband'
      - '--no-collector.bonding'
      - '--no-collector.conntrack'
      - '--no-collector.fibrechannel'
      - '--no-collector.nfs'
      - '--no-collector.nfsd'
      - '--no-collector.rapl'
      - '--no-collector.tapestats'
      - '--no-collector.zfs'
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - textfile:/var/lib/node_exporter/textfile_collector
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - iris
    depends_on:
      - oncall-web

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: backbox_exporter
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped
    networks:
      - iris
    ports:
      - '9115:9115'
    depends_on:
      - oncall-web

  custom_exporter:
    build: ./prometheus/custom_exporter
    container_name: custom_exporter
    networks:
      - iris
    ports:
      - '8000:8000'

networks:
  iris:
    name: iris
volumes:
  textfile:
