modules:
  http:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [ 200,302,301,304,401,403 ]
      method: GET
      follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false

  icmp:
    prober: icmp

  tcp:
    prober: tcp
