global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "oncall-app"
    metrics_path: /
    static_configs:
      - targets: ["oncall-web:8002"]

  - job_name: "custom-exporter"
    metrics_path: /
    static_configs:
      - targets: ["custom_exporter:8000"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http]
    static_configs:
      - targets: ["nginx:80"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: "nginx-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "blackbox-tcp"
    metrics_path: /probe
    params:
      module: [tcp]
    static_configs:
      - targets: ["nginx:80"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: "blackbox-icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: ["nginx"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: "my-prober"
    metrics_path: "/"
    static_configs:
      - targets: ["my_prober:9081"]
